#!/usr/bin/env R
install.packages("tidyverse")
install.packages('RPostgreSQL')
install.packages("BiocManager")
BiocManager::install("rhdf5")
install.packages("smotefamily")
install.packages("imager")
install.packages("gridExtra")
install.packages("haven")
install.packages("RcppTOML")
install.packages("rjson")
